services:
  - type: web
    name: to_do_app
    env: python
    buildCommand: |
      npm install
      npm run build
      python manage.py collectstatic --noinput
    startCommand: gunicorn myproject.wsgi:application
    envVars:
      - key: SECRET_KEY
        value: "your-secret-key"
    plan: free